name: CI

on:
  push:
    branches:
      - main
  pull_request:
  tags:

jobs:
  CI:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - run:  |
          mkdir ci-dependencies
          cd ci-dependencies
          curl -O https://skyapm.github.io/ci-assist/jars/ojdbc14-10.2.0.4.0.jar
          mvn install:install-file  -Dfile=ojdbc14-10.2.0.4.0.jar  -DgroupId=com.oracle  -DartifactId=ojdbc14 -Dversion=10.2.0.4.0 -Dpackaging=jar
          curl -O https://skyapm.github.io/ci-assist/jars/resin-4.0.41.jar
          mvn install:install-file  -Dfile=resin-4.0.41.jar  -DgroupId=com.caucho  -DartifactId=resin -Dversion=4.0.41 -Dpackaging=jar
          cd ..
      
      - run: mvn clean install


